version : 0.2
phases: 
  install:
    runtime-versions: 
      nodejs: 20
    commands:
      - echo "Installing dependencies...."
      - npm install
      - npm install -g @angular/cli@14.0.7
  build:
    commands:
      - echo "building angular project...."
      - ng build --configuration production --aot
  post_build:  
    commands:
      - echo "updating files in s3 bucket..."
      - aws s3 sync docs/ s3://kxnwar.com --delete