version : 0.2
phases: 
  install:
    runtime-versions: 
      nodejs: 12
    commands:
      - echo "Installing dependencies...."
      - npm install
      - npm install -g @angular/cli@10.0.8
    build:
      commands:
        - echo "building angular project...."
        - ng build --configuration production --aot
    post_build:  
      commands:
      - echo "updating files in s3 bucket..."
      - aws s3 sync dist/webapp s3://kanwarwebapp2024 --delete

      